# Generated by Django 5.1.1 on 2024-10-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='watchAgin',
            field=models.BooleanField(default=False),
        ),
    ]
